### ISSUE TITLE
chaintip is a bitcoin cash bounties bot that integrates directly into github

### ISSUE THREAD

**Issue by adangert** [djadmin/awesome-bug-bounty#20]
info is here
https://github.com/chaintip/bounties

**Comment by adangert** [comment]
@chaintip

**Comment by chaintip** [comment]
`0.0005 BCH`| `~   0.52 USD` has [been tipped](https://explorer.bitcoin.com/bch/address/bitcoincash:qqh0ld4vptyjgf2j0hjdd7vtxw8wlrapdvs3hkxq9n) to this issue by @adangert.
To claim [this bounty](http://github.chaintip.org/chaintip/bounties/issues/23), get a pull request merged with ```@chaintip fixes #20``` in the creation comment.

**Comment by chaintip** [comment]
`0 BCH`| `~   0.00 USD` has now been tipped to this issue.
To claim [this bounty](http://github.chaintip.org/chaintip/bounties/issues/23), get a pull request merged with ```@chaintip fixes #20``` in the creation comment.
